site_url: https://seabasmedia.netlify.app/
logo_url: https://seabasmedia.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    multiple: true
    cloud_name: seabas-media
    api_key: 733379514124262

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    slug: '{{slug}}'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
  - label: 'Home Page'
    name: 'home'
    slug: '{{slug}}'
    files:
      - label: 'About Me'
        name: 'aboutme'
        file: 'content/home/aboutme.md'
        format: 'markdown'
        fields:
          - { label: 'About Me Text', name: 'aboutmetext', widget: 'text' }
          - { label: 'About Me Image', name: 'aboutmeimage', widget: 'image' }
      - label: 'Home Gallery'
        name: 'homegallery'
        file: 'content/home/homegallery.md'
        format: 'markdown'
        fields:
          - {
              label: 'Home Gallery Images',
              name: 'homegalleryimages',
              widget: 'list',
              hint: 'must upload 4 pictures to keep layout of home page gallery',
              max: 4,
              min: 4,
              allow_add: true,
              collapsed: false,
              field: {
                  label: 'Image',
                  name: 'image',
                  # allow_multiple: false,
                  widget: 'image',
                  media_library: { config: { multiple: false } },
                },
            }

  - label: 'Galleries'
    label_singular: 'Gallery'
    name: 'gallery'
    title: 'gallery'
    slug: '{{slug}}'
    create: true
    # identifier_field: name
    # preview_path: '/gallery/{{filename}}.{{extension}}'
    preview_path: '/gallery'
    editor:
      preview: false
    folder: 'content/gallery'
    required: false
    sortable_fields: ['position']
    view_groups:
      - label: Section
        field: section
        pattern: 'Photography|Video|Graphic Design'
    fields:
      - label: 'Gallery Title'
        name: 'title'
        widget: 'string'
      - label: 'Section'
        name: 'section'
        widget: 'select'
        options: ['Photography', 'Video', 'Graphic Design']
      - label: 'Position'
        name: 'position'
        widget: 'number'
        hint: 'Order in which gallery will be displayed relative to section'
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: true
        summary: '{{'
        collapsed: false
        field: { label: 'Image', name: 'image', widget: 'image' }
